branches:
  except:
    - /^v[0-9]/
    - gh-pages

language: ruby

rvm:
  - 2.2.4

sudo: false

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

addons:
  apt:
    packages:
    - lftp

install:
  - gem install jekyll

script:
  - jekyll b

after_success:
  - cd _site
# Publish to live host via FTP
  - lftp -c "set ftp:list-options -a; set ssl:verify-certificate false; open ${FTP_LOGIN}; mirror --reverse --delete --verbose --allow-suid --no-umask --parallel=2"
# Publish to gh-pages, too
  - git init
  - git config user.name "Travis CI"
  - git config user.email "github@travis.example"
  - git add .
  - git commit -m "Deploy to GitHub Pages"
  - git push --force --quiet "https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git" master:gh-pages > /dev/null 2>&1
