title: BarCamp RheinMain
barcamp: 2017
baseurl: "" # the subpath of your site, e.g. /blog
url: http://static.barcamp-rheinmain.de

# Build settings
markdown: kramdown

keep_files: [vendor, status]
timezone: Europe/Berlin
